server:
  port: 8080

spring:
    datasource:
        name: mysql_test
        type: com.alibaba.druid.pool.DruidDataSource
        #druid相关配置
        druid:
          #监控统计拦截的filters
          filters: stat
          driver-class-name: com.mysql.jdbc.Driver
          #基本属性
#          url: jdbc:mysql://localhost:3306/ips_new?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
#          username: root
#          password: root
          url: jdbc:mysql://118.178.84.40:3306/ips_new?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
          username: root
          password: MageNB9527
          #配置初始化大小/最小/最大
          initial-size: 1
          min-idle: 1
          max-active: 20
          #获取连接等待超时时间
          max-wait: 60000
          #间隔多久进行一次检测，检测需要关闭的空闲连接
          time-between-eviction-runs-millis: 60000
          #一个连接在池中最小生存的时间
          min-evictable-idle-time-millis: 300000
          validation-query: SELECT 'x'
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
          pool-prepared-statements: false
          max-pool-prepared-statement-per-connection-size: 20

    aop:
      auto: true
      proxy-target-class: true
    servlet:
          multipart:
            max-file-size: 10Mb
            max-request-size: 100Mb

    devtools:
        restart:
            restart: true
            additional-paths: src/main/java

  #activemq
    activemq:
        broker-url: tcp://118.178.84.40:61616
#        broker-url: tcp://localhost:61616
        user: admin
        password: admin
        pool:
            enabled: true
            max-connections: 50
            expiry-timeout: 10000
            idle-timeout: 30000

    #### 开启发布订阅
    jms:
      pub-sub-domain: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.supadata.pojo


#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check

swagger:
    show: true


#本项目配置项
config:
    WINPATH: D:\\data\\ips\\
    LINUXDOCPATH: /data/ips/
    SERVICEURL: http://pad.supadata.cn/ips/
#    SERVICEURL: http://localhost:8080/
    #SERVICEURL: http://10.69.3.200:8080/ips/
    DESKEY: pengxiuxiaosupadata_test

#mqtt配置项
mqtt:
  host: tcp://118.178.84.40:1883
#  host: tcp://localhost:1883
  subTopic: /messagesub/event
  pubTopic: /messagepush/event/
  clientId: server22
  userName: admin
  passWord: admin
  region: 8